# -*- coding: utf-8 -*-
"""Hoteles_reservas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zi4b50CV_ZPyMkpWrTyCeSgHOcpHpEWO

Programa que permite realizar varias aacciones sobre  el archivo de
hoteles, clientes y reservas.

Este programa permite trabajar sobre tres archivos JSON :
  1. Hoteles.json - Contiene información de los hoteles.
     - Permite crear, consultar, modificar y borrar registros
  2. clientes.json - Contiene  información de los clients.
     - Permite crear, consultar, modificar y borrar registros
  3. reservas.json - Contiene información de las reservas.
     - Permite crear, consultar y borrar registros

El resultado se muestra en pantalla y en cada accion se guarda directamente
en cada archivo.
"""

import json
import os

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Definir constantes para las rutas de archivos
HOTELES_FILE = (
    "/content/drive/MyDrive/Calidad_software/Semana6/hoteles.json"
)
CLIENTES_FILE = (
    "/content/drive/MyDrive/Calidad_software/Semana6/clientes.json"
)
RESERVAS_FILE = (
    "/content/drive/MyDrive/Calidad_software/Semana6/reservas.json"
)


class GestorHoteles:
    """
    Clase que permite leer y escribir en el archivo que
    se requiera
    """
    @staticmethod
    def leer_archivo(ruta):
        """
        Leer archivo
        """
        if not os.path.exists(ruta):
            return []
        try:
            with open(ruta, 'r', encoding='utf-8') as file:
                return json.load(file)
        except (json.JSONDecodeError, IOError) as e:
            print(f"Error al leer {ruta}: {e}")
            return []

    @staticmethod
    def escribir_archivo(ruta, data):
        """
        Escribir archivo
        """
        try:
            with open(ruta, 'w', encoding='utf-8') as file:
                json.dump(data, file, indent=4)
        except IOError as e:
            print(f"Error al escribir {ruta}: {e}")


class Hotel:
    """
    Se define la clase hotel donde tendra varias
    funciones crear, modificar, eliminar, consultar
    """
    ARCHIVO = HOTELES_FILE

    def __init__(self, hotel_data):
        """
        Inicializa el objeto Hotel a partir de
        un diccionario con los parámetros.
        """
        self.id_hotel = hotel_data.get('id_hotel')
        self.nombre = hotel_data.get('nombre')
        self.ubicacion = hotel_data.get('ubicacion')
        self.habitaciones_disponibles = hotel_data.get(
            'habitaciones_disponibles')
        self.numero_estrellas = hotel_data.get('numero_estrellas')

    def to_dict(self):
        """
        Archivo
        """
        return self.__dict__

    @classmethod
    def crear_hotel(cls, hotel_data):
        """
        Crear registro hotel
        """
        hoteles = GestorHoteles.leer_archivo(cls.ARCHIVO)

        # Verificar si el ID ya existe
        if any(hotel["id_hotel"] ==
               hotel_data["id_hotel"] for hotel in hoteles):
            print(f"Error: Ya existe un hotel con ID "
                  f"{hotel_data['id_hotel']}.")
            return

        # Agregar nuevo hotel
        hoteles.append(hotel_data)
        GestorHoteles.escribir_archivo(cls.ARCHIVO, hoteles)
        print("Hotel agregado exitosamente.")

    @classmethod
    def eliminar_hotel(cls, id_hotel):
        """
        eliminar registro hotel
        """
        hoteles = GestorHoteles.leer_archivo(cls.ARCHIVO)
        hoteles = [h for h in hoteles if h['id_hotel'] != id_hotel]
        GestorHoteles.escribir_archivo(cls.ARCHIVO, hoteles)
        print(f"Hotel con ID {id_hotel} eliminado.")

    @classmethod
    def modificar_hotel(cls, id_hotel, datos_actualizados):
        """
        modificar registro hotel
        """
        hoteles = GestorHoteles.leer_archivo(cls.ARCHIVO)
        for hotel in hoteles:
            if hotel['id_hotel'] == id_hotel:
                for key, value in datos_actualizados.items():
                    if value is not None:  # Si no es None, actualiza el campo
                        hotel[key] = value
                GestorHoteles.escribir_archivo(cls.ARCHIVO, hoteles)
                print("Hotel actualizado exitosamente.")
                return
        print(f"Hotel con ID {id_hotel} no encontrado.")

    @classmethod
    def mostrar_info(cls, id_hotel=None):
        """
        consultar registro hotel
        """
        hoteles = GestorHoteles.leer_archivo(cls.ARCHIVO)
        if id_hotel:
            try:
                id_hotel = int(id_hotel)  # Convertir a entero
            except ValueError:
                print("ID inválido. Debe ser un número.")
                return

            for hotel in hoteles:
                if hotel['id_hotel'] == id_hotel:
                    print(json.dumps(hotel, indent=4))
                    return
            print(f"Hotel con ID {id_hotel} no encontrado")
        else:
            print(json.dumps(hoteles, indent=4))


class Cliente:
    """
    Se define la clase cliente donde tendra varias
    funciones crear, modificar, eliminar, consultar
    """
    ARCHIVO = CLIENTES_FILE

    def __init__(self, id_cliente, nombre, email):
        self.id_cliente = id_cliente
        self.nombre = nombre
        self.email = email

    def to_dict(self):
        """
        archivo
        """
        return self.__dict__

    @classmethod
    def crear_cliente(cls, id_cliente, nombre, email):
        """
        Crear registro cliente
        """
        clientes = GestorHoteles.leer_archivo(cls.ARCHIVO)

        # Verificar si el ID ya existe
        if any(cliente["id_cliente"] == id_cliente for cliente in clientes):
            print(f"Error: Ya existe un cliente con ID {id_cliente}.")
            return

        # Agregar nuevo cliente
        clientes.append(Cliente(id_cliente, nombre, email).to_dict())
        GestorHoteles.escribir_archivo(cls.ARCHIVO, clientes)
        print("Cliente agregado exitosamente.")

    @classmethod
    def eliminar_cliente(cls, id_cliente):
        """
        eliminar registro cliente
        """
        clientes = GestorHoteles.leer_archivo(cls.ARCHIVO)
        clientes = [c for c in clientes if c['id_cliente'] != id_cliente]
        GestorHoteles.escribir_archivo(cls.ARCHIVO, clientes)

    @classmethod
    def modificar_cliente(cls, id_cliente, nombre=None, email=None):
        """
        modificar registro cliente
        """
        clientes = GestorHoteles.leer_archivo(cls.ARCHIVO)
        for cliente in clientes:
            if cliente['id_cliente'] == id_cliente:
                if nombre is not None:
                    cliente['nombre'] = nombre
                if email is not None:
                    cliente['email'] = email
                GestorHoteles.escribir_archivo(cls.ARCHIVO, clientes)
                print("Cliente actualizado")
                return
        print("Cliente no encontrado")
        return

    @classmethod
    def mostrar_info(cls, id_cliente=None):
        """
        consultar registro cliente
        """
        clientes = GestorHoteles.leer_archivo(cls.ARCHIVO)
        if id_cliente:
            try:
                id_cliente = int(id_cliente)  # Convertir a entero
            except ValueError:
                print("ID inválido. Debe ser un número.")
                return
            for cliente in clientes:
                if cliente['id_cliente'] == id_cliente:
                    print(json.dumps(cliente, indent=4))
                    return
            print(f"Cliente con ID {id_cliente} no encontrado")
        else:
            print(json.dumps(clientes, indent=4))


class Reserva:
    """
    Definir clase reserva
    """
    ARCHIVO = RESERVAS_FILE

    def __init__(self, id_reserva, id_cliente, id_hotel):
        self.id_reserva = id_reserva
        self.id_cliente = id_cliente
        self.id_hotel = id_hotel

    def to_dict(self):
        """
        Archivo
        """
        return self.__dict__

    @classmethod
    def crear_reserva(cls, id_reserva, id_cliente, id_hotel):
        """
        Crear registro reserva
        """
        reservas = GestorHoteles.leer_archivo(cls.ARCHIVO)

        # Verificar si el ID ya existe
        if any(reserva["id_reserva"] == id_reserva for reserva in reservas):
            print(f"Error: Ya existe una reserva con ID {id_reserva}.")
            return

        # Agregar nueva reserva
        reservas.append(Reserva(id_reserva, id_cliente, id_hotel).to_dict())
        GestorHoteles.escribir_archivo(cls.ARCHIVO, reservas)
        print("Reserva agregada exitosamente.")

    @classmethod
    def cancelar_reserva(cls, id_reserva):
        """
        Cancelar registro reserva
        """
        reservas = GestorHoteles.leer_archivo(cls.ARCHIVO)
        reservas = [r for r in reservas if r['id_reserva'] != id_reserva]
        GestorHoteles.escribir_archivo(cls.ARCHIVO, reservas)

    @classmethod
    def mostrar_info(cls, id_reserva=None):
        """
        Mostrar registro reserva
        """
        reservas = GestorHoteles.leer_archivo(cls.ARCHIVO)
        if id_reserva:
            try:
                id_reserva = int(id_reserva)  # Convertir a entero
            except ValueError:
                print("ID inválido. Debe ser un número.")
                return

            for reserva in reservas:
                if reserva['id_reserva'] == id_reserva:
                    print(json.dumps(reserva, indent=4))
                    return
            print(f"Reserva con ID {id_reserva} no encontrada")
        else:
            print(json.dumps(reservas, indent=4))


def prueba1():
    """
    Se define funciones para en este caso
    consultar la informacion de cada uno de los archivos
    """
    while True:
        print("\nSeleccione una opción:")
        print("1. Mostrar hoteles")
        print("2. Mostrar clientes")
        print("3. Mostrar reservas")
        print("4. Salir")

        opcion = input("Ingrese el número de la opción: ")

        if opcion == "1":
            id_hotel = input(
                "Ingrese el ID del hotel (o presione Enter para ver todos): "
                ).strip()
            Hotel.mostrar_info(id_hotel if id_hotel else None)

        elif opcion == "2":
            id_cliente = input(
                "Ingrese el ID del cliente (o presione Enter para ver todos): "
                ).strip()
            Cliente.mostrar_info(id_cliente if id_cliente else None)

        elif opcion == "3":
            id_reserva = input(
                "Ingrese el ID de la reserva(o presione Enter ver todos): "
                ).strip()
            Reserva.mostrar_info(id_reserva if id_reserva else None)

        elif opcion == "4":
            print("Saliendo...")
            break
        else:
            print("Opción no válida, intente de nuevo.")


if __name__ == "__main__":
    prueba1()


# Ejemplo de uso
def prueba2():
    """
    Se dejecutan las funciones para crear registros
    en cada uno de los archivos
    """
    # Hotel.crear_hotel(3, "Hotel Sol", "Santa Martha", 100, 5)
    # Hotel.crear_hotel(4, "Sol caribe", "Barranquilla", 85, 3)
    # Hotel.crear_hotel(10, "Hotel Amazonas", "Amazonas", 30, 4)
    # Hotel.crear_hotel(11, "Hotel Riviera", "Mexico", 150, 5)
    hotel_data = {
      "id_hotel": 3,
      "nombre": "Hotel Sol",
      "ubicacion": "Santa Martha",
      "habitaciones_disponibles": 100,
      "numero_estrellas": 5
    }
    Hotel.crear_hotel(hotel_data)
    Cliente.crear_cliente(3, "Maritza Guerrero", "malige1@hotmail.com")
    Cliente.crear_cliente(5, "Oscar Rodriguez", "OscarR@gmail.com")
    Cliente.crear_cliente(4, "Elim Gutierrez", "ElimG@gmail.com")
    Cliente.crear_cliente(6, "Alfonso Ospina", "AlfonsoO@hotmail.com")
    Reserva.crear_reserva(3, 1, 1)
    Reserva.crear_reserva(3, 3, 3)
    Reserva.crear_reserva(4, 4, 3)
    Reserva.crear_reserva(5, 10, 6)


if __name__ == "__main__":
    prueba2()


# Ejemplo de uso modificacion
def prueba3():
    """
    Se ejecutan las funciones para modificar registros
    en cada uno de los archivos
    """
    # Hotel.modificar_hotel(2, ubicacion='Cartagena')
    # Hotel.modificar_hotel(12, ubicacion='Colombia')
    # Hotel.modificar_hotel(4, nombre='Sol Caribe y Son')
    datos_actualizados = {
       "nombre": "Nuevo Nombre de Hotel",
       "ubicacion": "Nueva Ubicacion",
       "habitaciones_disponibles": 60
    }
    Hotel.modificar_hotel(1, datos_actualizados)
    Cliente.modificar_cliente(1, nombre="Juan Carlos Fernandez")
    Cliente.modificar_cliente(7, nombre="Omar Geles")
    Cliente.modificar_cliente(4, email='ElimGM@gmail.com')


if __name__ == "__main__":
    prueba3()
